In [9]:
import pandas as pd
import seaborn as sns
import numpy as np
nhane = pd.read_csv('my_nhane.csv')
days = pd.DataFrame({'date':pd.date_range('2017-01-01','2019-12-31',freq='D')})
date = days.sample(n=nhane.shape[0],replace=True)
date = date.reset_index()
date.drop(columns='index',inplace=True)
nhane['interview_day'] = date

In [10]:
nhane.head()

,Unnamed: 0,SEQN,BPQ080,BPQ100D,BMDSTATS,BMXHT,BMXBMI,BMDBMIC,BMXLEG,BMXWAIST,...,DIQ070,CDQ010,ALQ151,OCQ180,LUAXSTAT,LUXCAPM,LBXIN,MCQ053,LBXTC,interview_day
0,1,109263,NaN,NaN,No body measures exam data,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,2017-05-29
1,2,109264,NaN,NaN,Complete data for age group,154.7,17.6,Normal weight,36.3,63.8,...,NaN,NaN,NaN,NaN,Ineligible,NaN,6.05,No,166.0,2019-12-16
2,3,109265,NaN,NaN,Complete data for age group,89.3,15.0,Normal weight,NaN,41.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,2017-08-11
3,4,109266,Yes,NaN,Complete data for age group,160.2,37.8,NaN,40.8,117.9,...,No,NaN,No,40.0,Complete,277.0,NaN,No,195.0,2019-04-03
4,5,109267,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,40.0,NaN,NaN,NaN,No,NaN,2018-09-28

In [11]:
nhane[['SEQN','BMXBMI','RIDSTATR','RIDRETH1','BMXHT']].head()

,SEQN,BMXBMI,RIDSTATR,RIDRETH1,BMXHT
0,109263,NaN,Both interviewed and MEC examined,Other Race - Including Multi-Racial,NaN
1,109264,17.6,Both interviewed and MEC examined,Mexican American,154.7
2,109265,15.0,Both interviewed and MEC examined,Non-Hispanic White,89.3
3,109266,37.8,Both interviewed and MEC examined,Other Race - Including Multi-Racial,160.2
4,109267,NaN,Interviewed only,Other Hispanic,NaN

In [12]:
# nhane.shape

# nhane['BMDBMIC']
# nhane[['BMDBMIC','SEQN']]

# nhane.loc[999]
# nhane.loc[:, 'BMDBMIC']
# nhane.loc[3:5, 'BMDBMIC']
# nhane.head(12)

# nhane.loc[list(range(4)) + [8], ['BMDBMIC', 'SEQN']]
# nhane.loc[[1,3,5], 'SEQN':'BMDBMIC']

In [13]:
# nhane.loc[25, 'BMXHT'] = 200
# nhane.loc[25, ['BMDBMIC', 'BMXHT']]
# nhane.iloc[0:3, 2]
# nhane.iloc[[1,2,3], [4,5,6]]
nhane.iloc[list(range(10, 81)) + [90], [4,5,6]]

                                     BMDSTATS  BMXHT  BMXBMI
10                Complete data for age group  184.2    21.9
11                Complete data for age group  185.3    30.2
12  Partial:  Only height and weight obtained  120.4    14.4
13                Complete data for age group    NaN     NaN
14                Complete data for age group  162.0    18.6
..                                        ...    ...     ...
77                Complete data for age group  172.9    46.2
78                Complete data for age group  125.4    15.8
79                Complete data for age group  161.0    35.5
80                                        NaN    NaN     NaN
90                Complete data for age group  146.7    21.4

[72 rows x 3 columns]

In [14]:
tmp = nhane.loc[1:8, ['SEQN','BMXBMI','RIDSTATR','RIDRETH1','BMXLEG','BMXWAIST']]
tmp = tmp.set_axis(['A','B','C','D','E','F','G','H'], axis='index',)
tmp

tmp.loc[['G', 'H']]

,SEQN,BMXBMI,RIDSTATR,RIDRETH1,BMXLEG,BMXWAIST
G,109270,30.9,Both interviewed and MEC examined,Non-Hispanic Black,42.6,91.4
H,109271,29.7,Both interviewed and MEC examined,Non-Hispanic White,40.1,120.4

In [15]:
nhane['BMXBMI'] > 25
nhane[nhane['BMXBMI'] > 25]

nhane['RIDRETH1'] == 'Non-Hispanic White'
nhane[nhane['RIDRETH1'] == 'Non-Hispanic White']

nhane[(nhane['BMXBMI'] >= 18.5) & (nhane['BMXBMI'] <= 24.9)]

nhane[nhane['BMXBMI'].isna()]
nhane['RIDSTATR'].unique()

<StringArray>
['Both interviewed and MEC examined', 'Interviewed only']
Length: 2, dtype: str

In [16]:
nhane.info()

<class 'pandas.DataFrame'>
RangeIndex: 15582 entries, 0 to 15581
Data columns (total 26 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     15582 non-null  int64
 1   SEQN           15582 non-null  int64
 2   BPQ080         10207 non-null  str
 3   BPQ100D        2751 non-null   str
 4   BMDSTATS       14321 non-null  str
 5   BMXHT          13177 non-null  float64
 6   BMXBMI         13157 non-null  float64
 7   BMDBMIC        4758 non-null   str
 8   BMXLEG         10996 non-null  float64
 9   BMXWAIST       12593 non-null  float64
 10  RIDSTATR       15582 non-null  str
 11  RIAGENDR       15582 non-null  str
 12  RIDAGEYR       15582 non-null  int64
 13  RIDRETH1       15582 non-null  str
 14  RIDRETH3       15582 non-null  str
 15  RIDEXMON       14321 non-null  str
 16  DIQ070         2684 non-null   str
 17  CDQ010         6440 non-null   str
 18  ALQ151         7509 non-null   str
 19  OCQ180         5378 non-null   float64
 20  LUAXSTAT       10421 non-null  str
 21  LUXCAPM        9708 non-null   float64
 22  LBXIN          4629 non-null   float64
 23  MCQ053         15007 non-null  str
 24  LBXTC          10840 non-null  float64
 25  interview_day  15582 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(8), int64(3), str(14)
memory usage: 3.1 MB

In [17]:
nhane['BMDSTATS'].value_counts()
nhane['BMDSTATS'].isnull()
nhane['BMDSTATS'].isna()

nhane[nhane['BMDSTATS'].isnull()]['BMDSTATS']

4        NaN
5        NaN
20       NaN
36       NaN
48       NaN
        ...
15488    NaN
15497    NaN
15532    NaN
15545    NaN
15568    NaN
Name: BMDSTATS, Length: 1261, dtype: str

In [22]:
nhane['interview_day'] = pd.to_datetime(nhane['interview_day'])

nhane['Day'] = nhane['interview_day'].dt.day
nhane['Month'] = nhane['interview_day'].dt.month
nhane['Year'] = nhane['interview_day'].dt.year
nhane['Dayname'] = nhane['interview_day'].dt.day_name()
nhane['Day_week'] = nhane['interview_day'].dt.day_of_week

nhane['Day'] = nhane['interview_day'].dt.day

nhane[['SEQN','interview_day','Day','Month','Dayname','Day_week']]

         SEQN interview_day  Day  Month    Dayname  Day_week
0      109263    2017-05-29   29      5     Monday         0
1      109264    2019-12-16   16     12     Monday         0
2      109265    2017-08-11   11      8     Friday         4
3      109266    2019-04-03    3      4  Wednesday         2
4      109267    2018-09-28   28      9     Friday         4
...       ...           ...  ...    ...        ...       ...
15577  115983    2017-10-02    2     10     Monday         0
15578  115984    2018-07-15   15      7     Sunday         6
15579  115985    2018-08-14   14      8    Tuesday         1
15580  115986    2017-12-20   20     12  Wednesday         2
15581  115987    2019-06-07    7      6     Friday         4

[15582 rows x 6 columns]

In [24]:
nhane['daydiff'] = nhane['interview_day'].diff()
nhane['daydiff'].head()
nhane[['interview_day','daydiff']].head()

  interview_day   daydiff
0    2017-05-29       NaT
1    2019-12-16  931 days
2    2017-08-11 -857 days
3    2019-04-03  600 days
4    2018-09-28 -187 days

In [26]:
nhane['daydiff'].dt.days<5
nhane[nhane['daydiff'].dt.days<5]['interview_day']

2       2017-08-11
4       2018-09-28
5       2017-03-08
7       2019-09-10
8       2017-08-18
           ...
15569   2018-06-07
15571   2018-01-06
15575   2017-05-17
15577   2017-10-02
15580   2017-12-20
Name: interview_day, Length: 7881, dtype: datetime64[us]

In [28]:
k = nhane['interview_day'].between('2017-02-15', '2018-01-15')
nhane[k]

,Unnamed: 0,SEQN,BPQ080,BPQ100D,BMDSTATS,BMXHT,BMXBMI,BMDBMIC,BMXLEG,BMXWAIST,...,LBXIN,MCQ053,LBXTC,interview_day,Day,Month,Year,Dayname,Day_week,daydiff
0,1,109263,NaN,NaN,No body measures exam data,NaN,NaN,NaN,NaN,NaN,...,NaN,No,NaN,2017-05-29,29,5,2017,Monday,0,NaT
2,3,109265,NaN,NaN,Complete data for age group,89.3,15.0,Normal weight,NaN,41.2,...,NaN,No,NaN,2017-08-11,11,8,2017,Friday,4,-857 days
5,6,109268,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,No,NaN,2017-03-08,8,3,2017,Wednesday,2,-569 days
8,9,109271,Yes,Yes,Complete data for age group,182.3,29.7,NaN,40.1,120.4,...,16.96,No,147.0,2017-08-18,18,8,2017,Friday,4,-753 days
9,10,109272,NaN,NaN,Complete data for age group,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2017-10-04,4,10,2017,Wednesday,2,47 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15565,6709,115971,NaN,NaN,Complete data for age group,100.0,14.7,Normal weight,NaN,46.2,...,NaN,No,NaN,2017-05-09,9,5,2017,Tuesday,1,-71 days
15571,6715,115977,NaN,NaN,Complete data for age group,135.9,25.7,Obese,32.0,84.2,...,NaN,No,NaN,2018-01-06,6,1,2018,Saturday,5,-160 days
15575,6719,115981,NaN,NaN,Complete data for age group,164.4,21.2,Normal weight,38.2,79.4,...,NaN,No,121.0,2017-05-17,17,5,2017,Wednesday,2,-786 days
15577,6721,115983,No,NaN,Complete data for age group,160.8,29.5,NaN,38.0,105.6,...,40.32,No,218.0,2017-10-02,2,10,2017,Monday,0,-780 days
15580,6724,115986,No,NaN,Complete data for age group,164.8,39.4,NaN,42.0,110.2,...,NaN,No,225.0,2017-12-20,20,12,2017,Wednesday,2,-237 days

In [30]:
nhane.tail(3)
nhane.sample(n=5)

,Unnamed: 0,SEQN,BPQ080,BPQ100D,BMDSTATS,BMXHT,BMXBMI,BMDBMIC,BMXLEG,BMXWAIST,...,LBXIN,MCQ053,LBXTC,interview_day,Day,Month,Year,Dayname,Day_week,daydiff
2196,2197,111459,Yes,No,Complete data for age group,184.6,30.0,NaN,42.5,118.5,...,NaN,No,234.0,2018-05-10,10,5,2018,Thursday,3,-528 days
15119,15120,124382,No,NaN,Complete data for age group,184.3,20.0,NaN,39.4,81.5,...,NaN,No,152.0,2019-02-11,11,2,2019,Monday,0,709 days
15415,15416,124678,NaN,NaN,Complete data for age group,107.1,13.5,Normal weight,NaN,48.2,...,NaN,No,122.0,2019-09-26,26,9,2019,Thursday,3,-12 days
14120,14121,123383,NaN,NaN,Complete data for age group,142.9,24.6,Obese,33.0,81.5,...,NaN,No,113.0,2017-06-15,15,6,2017,Thursday,3,-233 days
11567,11568,120830,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,No,NaN,2019-07-21,21,7,2019,Sunday,6,845 days

In [31]:
nhane.describe().T

,count,mean,min,25%,50%,75%,max,std
Unnamed: 0,15582.0,7778.99493,1.0,3896.25,7769.5,11664.75,15560.0,4488.935536
SEQN,15582.0,117040.99493,109263.0,113158.25,117031.5,120926.75,124822.0,4488.935536
BMXHT,13177.0,156.467003,78.3,151.1,162.0,171.3,199.6,22.639109
BMXBMI,13157.0,26.655362,11.9,20.4,25.8,31.4,92.3,8.41986
BMXLEG,10996.0,38.74468,24.8,36.0,38.9,41.5,55.0,4.132493
BMXWAIST,12593.0,89.659104,40.0,73.3,91.0,105.4,187.5,23.156093
RIDAGEYR,15582.0,33.735721,0.0,10.0,30.0,56.0,80.0,25.322085
OCQ180,5378.0,193.918929,5.0,31.0,40.0,46.0,99999.0,3807.572773
LUXCAPM,9708.0,257.571178,100.0,211.0,253.0,302.0,400.0,63.545593
LBXIN,4629.0,14.97919,0.71,6.31,10.18,16.61,512.5,22.838416
LBXTC,10840.0,177.456827,71.0,149.0,173.0,201.0,446.0,40.363195
interview_day,15582,2018-07-08 09:28:31.975356,2017-01-01 00:00:00,2017-10-08 00:00:00,2018-07-13 00:00:00,2019-04-14 00:00:00,2019-12-31 00:00:00,NaN
Day,15582.0,15.751893,1.0,8.0,16.0,23.0,31.0,8.833777
Month,15582.0,6.538506,1.0,4.0,7.0,10.0,12.0,3.459507
Year,15582.0,2018.016365,2017.0,2017.0,2018.0,2019.0,2019.0,0.818988
Day_week,15582.0,2.984213,0.0,1.0,3.0,5.0,6.0,2.001638
daydiff,15581,0 days 01:08:17.914126,-1087 days +00:00:00,-320 days +00:00:00,-2 days +00:00:00,325 days 00:00:00,1079 days 00:00:00,448 days 19:22:03.822189